apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: x76136zvc-go-gitops
  description: This is GitOps manifest for x76136zvc-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=x76136zvc-go
    backstage.io/kubernetes-id: x76136zvc-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: x76136zvc-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:x76136zvc-go
